---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"
    username: "{{ ansible_env.COLTE_USER }}"
    colte_dir: "{{ ansible_env.COLTE_DIR }}"
    ims_dir: "{{ colte_dir }}/lte_extras/ims"

  tasks:
    - name: check for environment vars
      fail: msg= "Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
      when: coltenv is not defined

# STEP ONE: sudo add the line "deb http://download.virtualbox.org/virtualbox/debian stretch contrib"
# to the file /etc/apt/sources.list.d/virtualbox.list
    - name: add virtualbox repo
      lineinfile:
        path: /etc/apt/sources.list.d/virtualbox.list
        line: "deb http://download.virtualbox.org/virtualbox/debian stretch contrib"
        create: yes
      become: yes

# wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
    - name: add oracle vbox key to apt
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
      become: yes

# apt update
# apt install virtualbox-5.2
    - name: install virtualbox
      apt:
        update_cache: yes
        name: "{{ item }}"
      become: yes
      with_items:
      - linux-headers-4.9.0-6-amd64
      - virtualbox-5.1
      - vagrant

# download the clearwater ims ovf VAGRANT BOX from (http://vm-images.cw-ngv.com/cw-aio.ova)
#    - name: download Clearwater IMS All-In-One Server
#      get_url:
#        url: http://vm-images.cw-ngv.com/cw-aio.ova
#        dest: "{{ ims_dir }}"

# ALTERNATE TO ABOVE STEP: for now, we just *assume* that the .box file already exists in
# the ims subdirectory. I want to figure out a better solution, maybe copy/paste via install
# script, or hosting at UW. Would like not to not DL 1.1 gb in this script.

# import the ovf file into Vagrant and turn it on!
    - name: import cw-aio.box into Vagrant
      shell: |
        vagrant box add cw-aio.box --name cw-ims
        vagrant up ims
      args:
        chdir: "{{ ims_dir }}"

# NOTE: HOW TO CONFIGURE??!?!?!? VAGRANT PLUS OTHER ANSIBLE SCRIPT?!?!?!?


    # WARNING: I WAS NEVER ABLE TO GET CLEARWATER-DOCKER USEFULLY WORKING. THE BELOW
    # COMMENTED-OUT CODE WORKS TO INSTALL/SETUP/RUN THE DOCKER IMAGES, BUT THEY SUCK.
    # DISREGARD CODE, I'M NOW USING THE VIRTUALBOX ALL-IN-ONE OVS FILE INSTEAD.

    # - name: apt-get docker-compose
    #   apt:
    #     name: docker-compose
    #   become: yes

    # (since stretch, apt-get docker doesn't work anymore so we have to manual install)
    # - name: manually download/install docker deb
    #   apt: 
    #     deb: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_17.03.0~ce-0~debian-stretch_amd64.deb
    #   become: yes


    # - name: git clone clearwater-docker
    #   git:
    #     repo: https://github.com/Metaswitch/clearwater-docker.git
    #     dest: "{{ ims_dir }}/clearwater-docker"

    # - name: build clearwater ims docker images
    #   shell: |
    #     sudo docker build -t clearwater/base base
    #     sudo docker-compose -f minimal-distributed.yaml up -d
    #   args:
    #     chdir: "{{ ims_dir }}/clearwater-docker"
    #   become: yes

    #- name: docker build clearwater ims
    #  docker_image:
    #    path: "{{ ims_dir }}/clearwater-docker/base"
    #    name: clearwater/base
    #  become: yes

    #     sudo docker-compose -f minimal-distributed.yaml up -d
    #- name: docker compose clearwater ims (start group of services)
    #  docker_service:
    #    project_src: "{{ ims_dir }}/clearwater-docker"
    #    files: minimal-distributed.yaml
    #  become: yes
