# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "epc" do |epc|
    epc.vm.box = "bento/ubuntu-17.10"

    # junk to set up the interface that the enb will connect over
    epc.vm.network "private_network", ip: "10.0.101.3", auto_config: false
    epc.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    epc.vm.provision 'shell', inline: "ifconfig eth1 10.0.101.3", run: "always"

    epc.vm.network "forwarded_port", guest: 80, host: 8080

    epc.vm.provision "ansible" do |ansible|
      ansible.playbook = "epc_playbook.yml"
    end
  end
end
