#!/bin/bash

PORT=8798
if [ "$1" != "" ]; then
	echo "Port specified as $1"
	PORT=$1
fi

echo "Running on $PORT"
source /usr/bin/video_webapp_env/bin/activate
python3.7 /usr/bin/video_webapp/manage.py runserver $PORT

