#!/bin/bash

# scripts check for this first line to know that vars were loaded
export COLTENV=1

# base directory for the whole project
export COLTE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# the user (NOT ROOT) who's installing all this stuff. should have accss to their
# home directory and be able to sudo. default value is (the current user).
export COLTE_USER=$USER

# default password for everything database related (mysql, phpmyadmin, etc.)
export COLTE_DBPASS="correcthorsebatterystaple"

# THE FOLLOWING ARE COMPILATION OPTIONS. They pertain to compiling in specific modules or not.
export COLTE_EPC=1
export COLTE_ENBRAINS=1
export COLTE_EMERGENCY_WEBSERVICES=0
export COLTE_WEBSERVICES=1