# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "epc" do |epc|
    epc.vm.box = "bento/debian-9.3"

# IDEALLY, this is the only line we need to write. In practice, the combo of
# Vagrant + Ubuntu > 15.10 has unresolved net config issues, unclear why.
#    epc.vm.network "private_network", ip: "10.0.101.3", auto_config: false
#    epc.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'
#    epc.vm.rpvision 'shell', inline: "ifconfig eth1 10.0.101.3", run: "always"
#    epc.vm.network "public_network", ip: "10.0.200.3"

# (If the issues ever get resolved, delete the lines below this comment)
    # epc.vm.provision 'shell', inline: "ifconfig eth1 up"
    # epc.vm.network "private_network", ip: "10.0.101.3", auto_config: false
    # epc.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    # epc.vm.provision 'shell', inline: "ifconfig eth1 10.0.101.3", run: "always"

#   epc.vm.network "public_network", ip: "10.0.200.3", auto_config: false
#   epc.vm.provision 'shell', inline: "ifconfig eth2 10.0.200.3", run: "always"

    epc.vm.network "forwarded_port", guest: 80, host: 8080

    epc.vm.provision "shell", inline: <<-SHELL
      apt-get install -y git
      git clone https://github.com/uw-ictd/colte.git /home/vagrant/colte
      chown -R vagrant:vagrant /home/vagrant/colte
    SHELL

#    epc.vm.provision "ansible" do |ansible|
#      ansible.playbook = "ansible/vagrant_playbook.yml"
#    end

  end
end
