#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file hss_db_add_mme
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
. $THIS_SCRIPT_PATH/../build/tools/build_helper


# arg 1 is mysql hostname  (ex: 127.0.0.1)
# arg 2 is hss username    (ex: hssadmin)
# arg 3 is hss password    (ex: admin)
# arg 4 is database name   (ex: oai_db)
# arg 5 is mme hostname    (ex: lionel-Z170X-UD3)
# arg 6 is mme realm       (ex: openair4G.eur)
function main(){
  EXPECTED_ARGS=6
  if [ $# -ne $EXPECTED_ARGS ]
  then
    echo_error "Usage: hss_db_add_mme mysql_hostname hssuser hsspass databasename mme_hostname mme_realm"
    return 1
  fi
  local mysql_hostname=$1
  local hss_username=$2
  local hss_password=$3
  local database_name=$4
  local mme_hostname=$5
  local mme_realm=$6
    
  Q1="INSERT INTO mmeidentity (mmehost, mmerealm) SELECT '$mme_hostname.$mme_realm', '$mme_realm' FROM DUAL \
   WHERE NOT EXISTS ( SELECT idmmeidentity FROM mmeidentity WHERE mmehost = '$mme_hostname.$mme_realm' )"
  mysql -h $mysql_hostname -u $hss_username --password=$hss_password $database_name -e "${Q1}"
  if [ $? -ne 0 ]; then
    echo_error "HSS: $database_name update table mmeidentity failed"
    return 1
  else
    echo_success "HSS: $database_name update table mmeidentity succeeded"
  fi
  return 0
}

main "$@" 

