#!/bin/bash

# link config file so that we can access it from /usr/local/etc/colte
mkdir -p /usr/local/etc/colte
ln -s /usr/bin/colte-webconf/.env /usr/local/etc/colte/webconf.env

# update and reconfigure system
colteconf update

# systemctl start as service
systemctl daemon-reload
systemctl start colte-webconf

echo "Installed CoLTE Web Configuration Tool"
