# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "epc" do |epc|
    epc.vm.box = "bento/debian-9.4"

    epc.vm.network "forwarded_port", guest: 80, host: 8080
    epc.vm.network "forwarded_port", guest: 3002, host: 8081
    epc.vm.network "forwarded_port", guest: 7999, host: 8082

    epc.vm.provision "shell", inline: <<-SHELL
      apt-get install -y git vim
      git clone https://github.com/uw-ictd/colte.git /home/vagrant/colte
      chown -R vagrant:vagrant /home/vagrant/colte
    SHELL

  end
end
