# SMS TODO: CHECK FOR INSTALLATION AND ABORT IF WE ALREADY HAVE THIS INSTALLED

# ---
# - hosts: all

#   sudo: yes
#   tasks:
    - name: libgtpnl - apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: libgtpnl - apt-get necessary packages
      apt:
        name: "{{ item }}"            
      with_items:
      - autoconf
      - automake
      - build-essential
      - libmnl-dev
      become: yes

    - name: libgtpnl - clone from my github copy
      git:
        repo: git://git.osmocom.org/libgtpnl
        dest: "{{ packages_dir }}/libgtpnl"

# NOTE: if this causes build failure, comment out become and just add sudo
    - name: libgtpnl - configure
      shell: |
        sudo autoreconf -fi
        ./configure
      args:
        chdir: "{{ packages_dir }}/libgtpnl"
      # become: yes

    - name: libgtpnl - build
      make:
        chdir: "{{ packages_dir }}/libgtpnl"

    - name: libgtpnl - install
      make:
        chdir: "{{ packages_dir }}/libgtpnl"
        target: install
      become: yes

    - name: libgtpnl - doing something?!?
      shell: |
        ldconfig
      args:
        chdir: "{{ packages_dir }}/libgtpnl"
      become: yes
