---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"
    build_enbrains: "{{ ansible_env.COLTE_ENBRAINS }}"
    colte_dir: "{{ ansible_env.COLTE_DIR }}"

    enbrains_dir: "{{ colte_dir }}/enbrains"

  tasks:
    - name: check for environment vars
      assert:
        that: "build_enbrains == 1"
        msg: "build_enbrains not set to 1"

    - name: enbrains - apt-get dependencies
      apt:
        name: "libevent-dev"
      become: yes

    - name: enbrains - build
      make:
        chdir: "{{ enbrains_dir }}"


