---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"
    colte_dir: "{{ ansible_env.COLTE_DIR }}"

    enbrains_dir: "{{ colte_dir }}/enbrains"

  tasks:
    - name: check for environment vars
      assert:
        that: "coltenv == 1"
        msg: "Killing ansible script, environment variables not set!"

    - name: enbrains - apt-get dependencies
      apt:
        name: "libevent-dev"
      become: yes

    - name: enbrains - build
      make:
        chdir: "{{ enbrains_dir }}"


