

    - name: ovs - apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: ovs - apt-get necessary packages
      apt:
        name: "{{ item }}"            
      with_items:
      - libssl-dev
      - libcap-ng-dev
      - python-pip
      - linux-headers-4.9.0-6-amd64
      become: yes

    # pip install six
    - name: ovs - pip install six
      pip:
        name: six

    # $SUDO rm -rf /tmp/gtp
    # mkdir /tmp/gtp
    # cd /tmp/gtp
    # git clone https://gitlab.eurecom.fr/oai/openair-cn-extras.git
    - name: ovs - clone from eurecom gitlab
      git:
        repo: https://gitlab.eurecom.fr/oai/openair-cn-extras
        dest: "{{ packages_dir }}/openair-cn-extras"

    - name: ovs - SHELL INSTALL
      shell: |
        make
        sudo make install
        sudo modprobe udp_tunnel
        sudo modprobe ip6_udp_tunnel
        sudo modprobe gtp
      args:
        chdir: "{{ packages_dir }}/openair-cn-extras/linux-4.9.0-gtp-module/"

    # $SUDO rm -rf /tmp/ovs
    # cd /tmp
    # git clone https://github.com/openvswitch/ovs.git
    # git checkout 31b88c97512b5dca9f1f6f73bb33292618eee88a
    - name: ovs - clone openvswitch from github 
      git:
        repo: https://github.com/openvswitch/ovs
        dest: "{{ packages_dir }}/ovs"
        version: 31b88c97512b5dca9f1f6f73bb33292618eee88a

    # cd ovs
    # git am /tmp/gtp/openair-cn-extras/ovs/0001-datapath-GPRS-Tunneling-Protocol-GTP-support.patch
    # git am /tmp/gtp/openair-cn-extras/ovs/0002-userspace-GPRS-Tunneling-Protocol-GTP-support.patch
    - name: ovs - copy patches
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
      - {src: "{{ packages_dir }}/openair-cn-extras/ovs/0001-datapath-GPRS-Tunneling-Protocol-GTP-support.patch", dest: "{{ packages_dir }}/ovs/p1.patch"}
      - {src: "{{ packages_dir }}/openair-cn-extras/ovs/0002-userspace-GPRS-Tunneling-Protocol-GTP-support.patch", dest: "{{ packages_dir }}/ovs/p2.patch"}

    - name: ovs - SHELL apply git amend patches
      shell: |
        git am p1.patch
        git am p2.patch
      args:
        chdir: "{{ packages_dir }}/ovs/"

    - name: ovs - SHELL make and install
      shell: |
        ./boot.sh
        ./configure --with-linux=/lib/modules/`uname -r`/build
        make -j`nproc`
        cat {{ packages_dir }}/openair-cn-extras/linux-4.9.0-gtp-module/Module.symvers >> datapath/linux/Module.symvers
        make
        sudo make modules_install
        sudo make install
        sudo mkdir -p /usr/local/etc/openvswitch
        sudo mkdir -p /usr/local/var/run/openvswitch
        sudo ovsdb-tool create /usr/local/etc/openvswitch/conf.db vswitchd/vswitch.ovsschema
      args:
        chdir: "{{ packages_dir }}/ovs/"
        
