#!/bin/bash

script=/usr/bin/colte/coltedb.py
version=0.9.5

display_help() {
    echo "COMMANDS:" >&2
    echo "   add {imsi msisdn ip key opc}: adds a user to the network"
    echo "   remove {imsi}: removes a user from the network"
    echo "   topup {imsi} {money}: adds money to a user's account"
    echo "   disable {imsi}: sets a user's balance to 0 and kicks them off the network"
    echo "   enable {imsi}: gives a user 10MB of data and adds them to the network"
    echo "   admin {imsi}: gives a user administrative privileges"
    echo "   noadmin {imsi}: removes a user's administrative privileges"
    # echo "   sync: runs a sync script to ensure that the database configuration is sane"
    echo "   reset: WIPES OUT the database and restores it to the sample default"
    echo "   help: displays this message and exits"
    # ANY OTHER VALUES?!?!?!
}

echo "coltedb: CoLTE Database Configuration Tool ($version)"

if [ "$#" -lt 1 ]; then
	display_help
	exit 1
fi

if [ "$1" = "help" ]; then
	display_help
	exit 1
fi

if [ "$EUID" -ne 0 ]; then
	echo "coltedb: Must run as root!"
	exit 1
fi

load_yml() {
	local var=$1
	local str=$(grep "$var" /usr/bin/colte/roles/configure/vars/main.yml)
	local val=${str//*$var: /}
	local res="${val%\"}"
	local res="${res#\"}"
	echo $res
}
user=$(load_yml "mysql_user")
pass=$(load_yml "mysql_password")
db=$(load_yml "mysql_db")

if [ "$1" = "add" ]; then
	if [ "$#" -ne 6 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb add imsi msisdn ip key opc\""
		exit 1
	fi
	python $script $user $pass $db $1 $2 $3 $4 $5 $6
	exit 0
fi

if [ "$1" = "remove" ]; then
	if [ "$#" -ne 2 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb remove imsi\""
		exit 1
	fi
	python $script $user $pass $db $1 $2
	exit 0
fi

if [ "$1" = "topup" ]; then
	if [ "$#" -ne 3 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb topup imsi money\""
		exit 1
	fi
	python $script $user $pass $db $1 $2 $3
	exit 0
fi

if [ "$1" = "disable" ]; then
	if [ "$#" -ne 2 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb disable imsi\""
		exit 1
	fi
	python $script $user $pass $db $1 $2
	exit 0
fi

if [ "$1" = "enable" ]; then
	if [ "$#" -ne 2 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb enable imsi\""
		exit 1
	fi
	python $script $user $pass $db $1 $2
	exit 0
fi

if [ "$1" = "admin" ]; then
	if [ "$#" -ne 2 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb admin imsi\""
		exit 1
	fi
	python $script $user $pass $db $1 $2
	exit 0
fi

if [ "$1" = "noadmin" ]; then
	if [ "$#" -ne 2 ]; then
		echo "coltedb: incorrect number of args, format is \"coltedb noadmin imsi\""
		exit 1
	fi
	python $script $user $pass $db $1 $2
	exit 0
fi

if [ "$1" = "reset" ]; then
	mysql -u $user -p$pass $db < /usr/local/etc/colte/sample_db.sql
	echo "coltedb: reset database."
	exit 0
fi

# if [ "$1" = "sync" ]; then
# 	if [ "$#" -ne 1 ]; then
# 		echo "coltedb: incorrect number of args, format is \"coltedb sync\""
# 		exit 1
# 	fi
# 	python $script sync
# fi

display_help
