# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
