#!/bin/bash

python3.5 -m pip install virtualenv
virtualenv -p python3.5 /usr/bin/ourtube_env
source /usr/bin/ourtube_env/bin/activate
python3.5 -m pip install -r /usr/bin/ourtube_data/requirements.txt
deactivate

systemctl daemon-reload

echo "Installed OurTube"
