#!/bin/bash

python3.7 -m pip install virtualenv
python3.7 -m virtualenv /usr/bin/ourtube_env
source /usr/bin/ourtube_env/bin/activate
python3.7 -m pip install -r /usr/bin/ourtube_data/requirements.txt
deactivate

systemctl daemon-reload

echo "Installed OurTube"
