aa: 
  english: Afar
  native: Afaraf
ab: 
  english: Abkhazian
  native: Аҧсуа
ae: 
  english: Avestan
  native: avesta
af: 
  english: Afrikaans
  native: Afrikaans
ak: 
  english: Akan
  native: Akan
am: 
  english: Amharic
  native: አማርኛ
an: 
  english: Aragonese
  native: Aragonés
ar: 
  english: Arabic
  native: العربية
as: 
  english: Assamese
  native: অসমীয়া
av: 
  english: Avaric
  native: Авар
ay: 
  english: Aymara
  native: Aymar aru
az: 
  english: Azerbaijani
  native: Azərbaycan
ba: 
  english: Bashkir
  native: Башҡорт
be: 
  english: Belarusian
  native: Беларуская
be-Tarask: 
  english: Belarusian (Taraškievica orthography)
  native: беларуская (тарашкевіца)
bg: 
  english: Bulgarian
  native: Български
bh: 
  english: Bihari
  native: भोजपुरी
bi: 
  english: Bislama
  native: Bislama
bm: 
  english: Bambara
  native: Bamanankan
bn: 
  english: Bengali
  native: বাংলা
bo: 
  english: Tibetan
  native: བོད་ཡིག
br: 
  english: Breton
  native: Brezhoneg
bs: 
  english: Bosnian
  native: Bosanski
ca: 
  english: Catalan
  native: Català
ce: 
  english: Chechen
  native: Нохчийн
ch: 
  english: Chamorro
  native: Chamoru
co: 
  english: Corsican
  native: Corsu
cr: 
  english: Cree
  native: ᓀᐦᐃᔭᐍᐏᐣ
cs: 
  english: Czech
  native: Česky
cu: 
  english: Church Slavic
  native: Словѣ́ньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ
cv: 
  english: Chuvash
  native: Чӑвашла
cy: 
  english: Welsh
  native: Cymraeg
da: 
  english: Danish
  native: Dansk
de: 
  english: German
  native: Deutsch
dsb: 
  english: Lower Sorbian
  native: Dolnoserbski
dv: 
  english: Divehi
  native: ދިވެހިބަސް
dz: 
  english: Dzongkha
  native: ཇོང་ཁ
ee: 
  english: Ewe
  native: Eʋegbe
el: 
  english: Greek
  native: Ελληνικά
en: 
  english: English
  native: English
eo: 
  english: Esperanto
  native: Esperanto
es: 
  english: Spanish
  native: Español
et: 
  english: Estonian
  native: Eesti
eu: 
  english: Basque
  native: Euskara
fa: 
  english: Persian
  native: فارسی
ff: 
  english: Fulah
  native: Fulfulde
fi: 
  english: Finnish
  native: Suomi
fj: 
  english: Fijian
  native: Na Vosa Vakaviti
fo: 
  english: Faroese
  native: Føroyskt
fr: 
  english: French
  native: Français
fur: 
  english: Friulian
  native: Furlan
fy: 
  english: Western Frisian
  native: Frysk
ga: 
  english: Irish
  native: Gaeilge
gd: 
  english: Scottish Gaelic
  native: Gàidhlig
gl: 
  english: Galician
  native: Galego
gn: 
  english: Guarani
  native: Avañe'ẽ
gsw: 
  english: Swiss German
  native: Alemannisch
gu: 
  english: Gujarati
  native: ગુજરાતી
gv: 
  english: Manx
  native: Gaelg
ha: 
  english: Hausa
  native: هَوُسَ
he: 
  english: Hebrew
  native: עברית
hi: 
  english: Hindi
  native: हिन्दी
ho: 
  english: Hiri Motu
  native: Hiri Motu
hr: 
  english: Croatian
  native: Hrvatski
hsb: 
  english: Upper Sorbian
  native: Hornjoserbsce
ht: 
  english: Haitian
  native: Kreyòl ayisyen
hu: 
  english: Hungarian
  native: Magyar
hy: 
  english: Armenian
  native: Հայերեն
hz: 
  english: Herero
  native: Otjiherero
ia: 
  english: Interlingua
  native: Interlingua
id: 
  english: Indonesian
  native: Bahasa Indonesia
ie: 
  english: Interlingue
  native: Interlingue
ig: 
  english: Igbo
  native: Igbo
ii: 
  english: Sichuan Yi
  native: ꆇꉙ
ik: 
  english: Inupiaq
  native: Iñupiak
io: 
  english: Ido
  native: Ido
is: 
  english: Icelandic
  native: Íslenska
it: 
  english: Italian
  native: Italiano
iu: 
  english: Inuktitut
  native: ᐃᓄᒃᑎᑐᑦ/inuktitut
ja: 
  english: Japanese
  native: 日本語
jv: 
  english: Javanese
  native: Basa Jawa
ka: 
  english: Georgian
  native: ქართული
kg: 
  english: Kongo
  native: Kongo
ki: 
  english: Kikuyu
  native: Gĩkũyũ
kj: 
  english: Kwanyama
  native: Kuanyama
kk: 
  english: Kazakh
  native: Қазақша
kl: 
  english: Kalaallisut
  native: Kalaallisut
km: 
  english: Khmer
  native: ភាសាខ្មែរ
kn: 
  english: Kannada
  native: ಕನ್ನಡ
ko: 
  english: Korean
  native: 한국어
kr: 
  english: Kanuri
  native: Kanuri
ks: 
  english: Kashmiri
  native: (كشميري)
ksh: 
  english: Ripoarisch
  native: Ripoarisch
ku: 
  english: Kurdish
  native: Kurdî / كوردی
kv: 
  english: Komi
  native: Коми
kw: 
  english: Cornish
  native: Kernowek
ky: 
  english: Kirghiz
  native: Кыргызча
la: 
  english: Latin
  native: Latina
lb: 
  english: Luxembourgish
  native: Lëtzebuergesch
lg: 
  english: Ganda
  native: Luganda
li: 
  english: Limburgish
  native: Limburgs
ln: 
  english: Lingala
  native: Lingála
lo: 
  english: Lao
  native: ລາວ
lt: 
  english: Lithuanian
  native: Lietuvių
lu: 
  english: Luba-Katanga
  native: ~
lv: 
  english: Latvian
  native: Latviešu
mg: 
  english: Malagasy
  native: Malagasy
mh: 
  english: Marshallese
  native: Kajin M̧ajeļ
mi: 
  english: Maori
  native: Māori
mk: 
  english: Macedonian
  native: Македонски
ml: 
  english: Malayalam
  native: മലയാളം
mn: 
  english: Mongolian
  native: Монгол
mo: 
  english: Moldavian
  native: Молдовеняскэ
mr: 
  english: Marathi
  native: मराठी
ms: 
  english: Malay
  native: Bahasa Melayu
mt: 
  english: Maltese
  native: Malti
my: 
  english: Burmese
  native: မြန်မာဘာသာ
na: 
  english: Nauru
  native: Dorerin Naoero
nb: 
  english: Norwegian Bokmål
  native: ‪Norsk (bokmål)‬
nd: 
  english: North Ndebele
  native: isiNdebele
nds: 
  english: Low German
  native: Plattdüütsch
ne: 
  english: Nepali
  native: नेपाली
ng: 
  english: Ndonga
  native: Owambo
nl: 
  english: Dutch
  native: Nederlands
nn: 
  english: Norwegian Nynorsk
  native: ‪Norsk (nynorsk)‬
"no": 
  english: Norwegian (bokmål)‬
  native: ‪Norsk (bokmål)‬
nr: 
  english: South Ndebele
  native: isiNdebele
nv: 
  english: Navajo
  native: Diné bizaad
ny: 
  english: Nyanja
  native: Chi-Chewa
oc: 
  english: Occitan
  native: Occitan
oj: 
  english: Ojibwa
  native: ᐊᓂᔑᓈᐯᒧᐎᓐ
om: 
  english: Oromo
  native: Oromoo
or: 
  english: Oriya
  native: ଓଡ଼ିଆ
os: 
  english: Ossetic
  native: Иронау
pa: 
  english: Punjabi
  native: ਪੰਜਾਬੀ
pi: 
  english: Pali
  native: पािऴ
pl: 
  english: Polish
  native: Polski
ps: 
  english: Pashto
  native: پښتو
pt: 
  english: Portuguese
  native: Português
pt-BR: 
  english: Brazilian Portuguese
  native: Português do Brasil
qu: 
  english: Quechua
  native: Runa Simi
rm: 
  english: Rhaeto-Romance
  native: Rumantsch
rn: 
  english: Kirundi
  native: kiRundi
ro: 
  english: Romanian
  native: Română
ru: 
  english: Russian
  native: Русский
rw: 
  english: Kinyarwanda
  native: Ikinyarwanda
sa: 
  english: Sanskrit
  native: संस्कृत
sc: 
  english: Sardinian
  native: Sardu
sd: 
  english: Sindhi
  native: سنڌي
se: 
  english: Northern Sami
  native: Sámegiella
sg: 
  english: Sango
  native: Sängö
sh: 
  english: Serbo-Croatian
  native: Srpskohrvatski / Српскохрватски
si: 
  english: Sinhala
  native: සිංහල
sk: 
  english: Slovak
  native: Slovenčina
sl: 
  english: Slovenian
  native: Slovenščina
sm: 
  english: Samoan
  native: Gagana Samoa
sn: 
  english: Shona
  native: chiShona
so: 
  english: Somali
  native: Soomaaliga
sq: 
  english: Albanian
  native: Shqip
sr: 
  english: Serbian
  native: Српски
sr-Latn: 
  english: Serbian (Latin script)
  native: srpski (latinica)
ss: 
  english: Swati
  native: SiSwati
st: 
  english: Southern Sotho
  native: Sesotho
su: 
  english: Sundanese
  native: Basa Sunda
sv: 
  english: Swedish
  native: Svenska
sw: 
  english: Swahili
  native: Kiswahili
ta: 
  english: Tamil
  native: தமிழ்
te: 
  english: Telugu
  native: తెలుగు
tg: 
  english: Tajik
  native: Тоҷикӣ
th: 
  english: Thai
  native: ไทย
ti: 
  english: Tigrinya
  native: ትግርኛ
tk: 
  english: Turkmen
  native: Türkmençe
tl: 
  english: Tagalog
  native: Tagalog
tn: 
  english: Tswana
  native: Setswana
to: 
  english: Tonga
  native: lea faka-Tonga
tr: 
  english: Turkish
  native: Türkçe
ts: 
  english: Tsonga
  native: Xitsonga
tt: 
  english: Tatar
  native: Татарча/Tatarça
tw: 
  english: Twi
  native: Twi
ty: 
  english: Tahitian
  native: Reo Mā`ohi
ug: 
  english: Uighur
  native: Uyghurche‎ / ئۇيغۇرچە
uk: 
  english: Ukrainian
  native: Українська
ur: 
  english: Urdu
  native: اردو
uz: 
  english: Uzbek
  native: O'zbek
ve: 
  english: Venda
  native: Tshivenda
vi: 
  english: Vietnamese
  native: Tiếng Việt
vo: 
  english: Volapük
  native: Volapük
wa: 
  english: Walloon
  native: Walon
wo: 
  english: Wolof
  native: Wolof
xh: 
  english: Xhosa
  native: isiXhosa
yi: 
  english: Yiddish
  native: ייִדיש
yo: 
  english: Yoruba
  native: Yorùbá
za: 
  english: Zhuang
  native: Vahcuengh
zh: 
  english: Chinese
  native: 中文
zh-CN: 
  english: Chinese (China)
  native: ‪中文(中国大陆)‬
zh-TW: 
  english: Chinese (Taiwan)
  native: ‪中文(台灣)‬
zu: 
  english: Zulu
  native: isiZulu
