---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"

    build_epc: "{{ ansible_env.COLTE_EPC }}"
    build_billing: "{{ ansible_env.COLTE_BILLING }}"
    build_webgui: "{{ ansible_env.COLTE_WEBGUI }}"
    build_media: "{{ ansible_env.COLTE_MEDIA }}"
    build_wiki: "{{ ansible_env.COLTE_WIKI }}"
    build_maps: "{{ ansible_env.COLTE_MAP }}"
    build_chat: "{{ ansible_env.COLTE_CHAT }}"
    build_emergency: "{{ ansible_env.COLTE_EMERGENCY }}"
    build_zotac: "{{ ansible_env.COLTE_ZOTAC }}"

    username: "{{ ansible_env.COLTE_USER }}"
    mysql_password: "{{ ansible_env.COLTE_DBPASS }}"
    colte_rc_admin: "{{ ansible_env.COLTE_RC_ADMIN }}"
    colte_rc_pass: "{{ ansible_env.COLTE_RC_PASS }}"
    colte_rc_email: "{{ ansible_env.COLTE_RC_EMAIL }}"

    colte_dir: "{{ ansible_env.COLTE_DIR }}"
    chat_dir: "{{ colte_dir }}/lte_extras/chat"
    osm_dir: "{{ colte_dir }}/lte_extras/maps"
    emergency_dir: "{{ colte_dir }}/emergency"
    nginx_dir: "{{ colte_dir }}/lte_extras/nginx"
    bind_dir: "{{ colte_dir }}/lte_extras/bind"
    webgui_dir: "{{ colte_dir }}/lte_extras/webgui"
    ums_dir: "{{ colte_dir }}/lte_extras/media"
    wiki_dir: "{{ colte_dir }}/lte_extras/wiki"
    epc_dir: "{{ colte_dir }}/epc"
    packages_dir: "{{ colte_dir }}/packages"
    billing_dir: "{{ colte_dir }}/lte_extras/billing"

    enb_iface: "{{ ansible_env.COLTE_ENB_IFACE }}"
    enb_iface_addr: "{{ ansible_env.COLTE_ENB_IFACE_ADDR }}"
    wan_iface: "{{ ansible_env.COLTE_WAN_IFACE }}"
    lte_subnet: "{{ ansible_env.COLTE_LTE_SUBNET }}"
    network_name: "{{ ansible_env.COLTE_NETWORK_NAME }}"

  pre_tasks:
    - name: check for environment vars
      fail: msg= "Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
      when: coltenv is not defined

    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

  roles:
    - { role: epc, when: build_epc == '1' }
    - { role: billing, when: build_billing == '1' }
    - { role: webgui, when: build_webgui == '1' }
    - { role: media, when: build_media == '1' }
    - { role: wiki, when: build_wiki == '1' }
    - { role: maps, when: build_maps == '1' }
    - { role: chat, when: build_chat == '1' }
    - { role: emergency, when: build_emergency == '1' }
    - { role: zotac, when: build_zotac == '1' }

