---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"
    build_billing: "{{ ansible_env.COLTE_BILLING }}"
    username: "{{ ansible_env.COLTE_USER }}"
    mysql_password: "{{ ansible_env.COLTE_DBPASS }}"
    colte_rc_admin: "{{ ansible_env.COLTE_RC_ADMIN }}"
    colte_rc_pass: "{{ ansible_env.COLTE_RC_PASS }}"
    colte_rc_email: "{{ ansible_env.COLTE_RC_EMAIL }}"

    colte_dir: "{{ ansible_env.COLTE_DIR }}"
    chat_dir: "{{ colte_dir }}/lte_extras/chat"
    osm_dir: "{{ colte_dir }}/lte_extras/maps"
    emergency_dir: "{{ colte_dir }}/emergency"
    nginx_dir: "{{ colte_dir }}/lte_extras/nginx"
    webgui_dir: "{{ colte_dir }}/lte_extras/webgui"
    ums_dir: "{{ colte_dir }}/lte_extras/media"
    wiki_dir: "{{ colte_dir }}/lte_extras/wiki"
    epc_dir: "{{ colte_dir }}/epc"
    packages_dir: "{{ colte_dir }}/packages"
    billing_dir: "{{ colte_dir }}/lte_extras/billing"

    enb_iface: "{{ ansible_env.COLTE_ENB_IFACE }}"
    enb_iface_addr: "{{ ansible_env.COLTE_ENB_IFACE_ADDR }}"
    wan_iface: "{{ ansible_env.COLTE_WAN_IFACE }}"
    lte_subnet: "{{ ansible_env.COLTE_LTE_SUBNET }}"
    network_name: "{{ ansible_env.COLTE_NETWORK_NAME }}"

  pre_tasks:
    - name: check for environment vars
      fail: msg="Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
      when: coltenv is not defined

    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

  roles:
    - role: epc
    - role: maps
    - { role: billing, when: build_billing == '1' }

