---
  # tasks:
    # - name: check for environment vars
    #   fail: msg= "Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
    #   when: coltenv is not defined

  - name: stop apache2 sevice (IMPORTANT BEFORE INSTALLING nginx)
    service: name=apache2 state=stopped
    become: yes

  - name: apt-get nginx
    apt:
      name: "{{ item }}"
    become: yes
    with_items:
    - nginx

  - name: remove default nginx website (or server will not launch)
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: yes

    # normally just have to issue a "reloaded" but this is better practice
    # given that we also just installed nginx from apache
  - name: restart nginx
    service: name=nginx state=restarted
    become: yes

