name: Check formatting

on:
  # Triggers the workflow on push or pull request events for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm 7
        run: |
          npm install -g npm@7
          npm --version

      - name: Install prettier
        run: |
          npm install -g prettier

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install black
        working-directory: python
        run: poetry install

      - name: Run prettier over entire repo
        run: |
          prettier --version
          prettier --check .

      - name: Run black on python subdirectory
        working-directory: python
        run: |
          poetry run black --version
          poetry run black --check .
