# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # use official ubuntu image for virtualbox
  
  config.vm.define "osm" do |osm|
    osm.vm.box = "osm"
    osm.vm.synced_folder ".", "/srv/openstreetmap-website"
    osm.vm.network "forwarded_port", guest: 3000, host: 9084, auto_correct: true
    osm.vm.provision "shell", run: "always", inline: <<-SHELL
    	echo "starting rails app..."
    	sudo systemctl start osm_rails
	echo "started rail app"
    SHELL

#    osm.customize ["modifyvm", :id, "--memory", "1024"]
#    osm.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
